<MobileLayout>:
    md_bg_color: app.theme_cls.backgroundColor

    #MDBoxLayout:
    #    id: main_content
    #    orientation: 'vertical'
    #    size_hint_x: 1
    #
    #    MDLabel:
    #        text: "Mobile Layout - Main Content"
    #        theme_text_color: "Primary"
    #        font_style: "Headline"
    #        halign: "center"

<MainMobileColumn@BoxLayout>:
    id: main_column
    orientation: "vertical"
    size_hint_x: 1