<DesktopLayout>:
    md_bg_color: app.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: 'horizontal'
        spacing: 10
        padding: 10

        MainDesktopColumn:

        RightDesktopColumn:


<MainDesktopColumn>:
    id: main_desktop_column
    orientation: "vertical"
    size_hint_x: 0.6

<RightDesktopColumn>:
    id: right_desktop_column
    orientation: "vertical"
    size_hint_x: 0.4