#:import dp kivy.metrics.dp

<PaymentField>:
    style: "filled"
    orientation: "vertical"
    padding: dp(12)
    size_hint_y: None
    height: 0 if not self.is_visible else self.minimum_height
    opacity: 0 if not self.is_visible else 1
    md_bg_color: app.theme_cls.surfaceContainerHighColor
    
    # Row 1: Title and Info
    MDBoxLayout:
        orientation: "horizontal"
        spacing: dp(12)
        size_hint_y: None
        height: dp(24)
        
        MDLabel:
            text: root.title_text
            font_style: "Title"
            role: "medium"
            bold: True
            #size_hint_x: 0.4
            adaptive_size: True
        
        MDLabel:
            id: payment_info_label
            text: root.info_text
            font_style: "Body"
            role: "large"
            halign: "right"
            #theme_text_color: "Secondary"
            #size_hint_x: 0.6
            adaptive_size: True
            theme_text_color: "Custom"
            text_color: app.theme_cls.primaryColor

        MDWidget:
    
    # Row 2: Payment Buttons
    MDBoxLayout:
        orientation: "horizontal"
        spacing: dp(8)
        size_hint_y: None if root.buttons_row_visible else 0
        height: dp(48) if root.buttons_row_visible else 0
        
        # Primary wallet button (internal wallet)
        # Enabled only if wallet is NOT external
        MDButton:
            style: "filled" if not self.disabled else "outlined"
            size_hint_x: 1 if not root.is_wallet_external else 0
            #width: 0 if root.is_wallet_external else self.parent.width / 2 - dp(4)
            opacity: 1 if root.buttons_row_visible else 0
            disabled: not root.payment_enabled or root.is_wallet_external
            on_release: root.pay_with_internal_wallet()
            MDButtonIcon:
                icon: "wallet" if root.swap_direction == "kas2sat" else "lightning-bolt"
                disabled_color: app.theme_cls.onSecondaryContainerColor
            MDButtonText:
                text: ("Pay with Kaspa Wallet" if root.swap_direction == "kas2sat" else "Pay with LN Wallet")
                disabled_color: app.theme_cls.onSecondaryContainerColor
        
        # External wallet button (always visible)
        MDButton:
            style: "outlined"
            disabled: not root.payment_enabled
            opacity: 1 if root.buttons_row_visible else 0
            on_release: root.pay_with_external_wallet()
            MDButtonIcon:
                icon: "open-in-new"
            MDButtonText:
                text: ("Pay External (KAS)" if root.swap_direction == "kas2sat" else "Pay External (BTC)")

        MDWidget: